print(f"'test' == 'test'. I predict True. \n{'test' == 'test'}")
print(f"\n'test' == 'Test'. I predict False. \n{'test' == 'Test'}")
print(f"\n'test' == 'TeSt'.lower(). I predict True. \n{'test' == 'TeSt'.lower()}")
print(f"\n'test' != 'tesT'. I predict True. \n{'test' != 'tesT'}")
print(f"\n 0 == 0. I predict True. \n{0 == 0}")
print(f"\n 1 == 0. I predict False. \n{1 == 0}")
print(f"\n 0 != 3. I predict True. \n{0 != 3}")
print(f"\n 0 > 0. I predict False. \n{0 > 0}")
print(f"\n 0 >= 0. I predict True. \n{0 >= 0}")
print(f"\n 0 < 1. I predict True. \n{0 < 1}")
print(f"\n 0 == 0 and 0 > -1. I predict True. \n{(0 == 0) and (0 > -1)}")
print(f"\n 0 == 0 and 0 < -1. I predict False. \n{(0 == 0) and (0 < -1)}")
print(f"\n 0 == 0 or 0 < -1. I predict True. \n{(0 == 0) or (0 < -1)}")
print(f"\n 1 is in [1,2,3] I predict True. \n{1 in [1,2,3]}")
print(f"\n 4 is in [1,2,3] I predict False. \n{4 in [1,2,3]}")

